// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"certitrack/internal/config"
	"certitrack/internal/database"
	"certitrack/internal/handlers"
	"certitrack/internal/middleware"
	"certitrack/internal/repositories"
	"certitrack/internal/services"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeServer() (*ServerDependencies, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := database.Connect(configConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repositories.NewUserRepositoryImpl(db)
	authServiceImpl := services.NewAuthService(configConfig, userRepository)
	authHandler := handlers.NewAuthHandler(authServiceImpl)
	middlewareMiddleware := middleware.NewMiddleware(authServiceImpl)
	serverDependencies := &ServerDependencies{
		Config:      configConfig,
		DB:          db,
		AuthHandler: authHandler,
		Middleware:  middlewareMiddleware,
	}
	return serverDependencies, nil
}

// wire.go:

var (
	repositorySet = wire.NewSet(repositories.NewUserRepositoryImpl)

	serviceSet = wire.NewSet(services.NewAuthService, wire.Bind(new(services.AuthService), new(*services.AuthServiceImpl)))

	handlerSet = wire.NewSet(handlers.NewAuthHandler)

	middlewareSet = wire.NewSet(middleware.NewMiddleware)
)

type ServerDependencies struct {
	Config      *config.Config
	DB          *gorm.DB
	AuthHandler *handlers.AuthHandler
	Middleware  *middleware.Middleware
}
